/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=Bindings src/worker-configuration.d.ts` (hash: ff3ac1a666e5219aa11ded8c165d2463)
interface __BaseEnv_Bindings {
  ASSETS: Fetcher;
  RATE_LIMIT_SHARD: DurableObjectNamespace<import("./index").RateLimitShard>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "RateLimitShard";
  }
  interface Env extends __BaseEnv_Bindings {}
}
interface Bindings extends __BaseEnv_Bindings {}
