/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=Bindings src/worker-configuration.d.ts` (hash: de749fbf5c8eb7f0432b3bdc20dc09eb)
interface __BaseEnv_Bindings {
  ASSETS: Fetcher;
  SESSION_AEAD_KEY: string;
  SESSION_AEAD_KEY_VERSION: string;
  RATE_LIMIT_HMAC_KEY_V1: string;
  RATE_LIMIT_SHARD: DurableObjectNamespace<import("./index").RateLimitShard>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "RateLimitShard";
  }
  interface Env extends __BaseEnv_Bindings {}
}
interface Bindings extends __BaseEnv_Bindings {}
